### ISSUE TITLE
Need help understanding new settings

### ISSUE THREAD

**Issue by Scott1009** [JuiceRescue/juicepassproxy#118]
I realized that my proxy had stopped working because of the encrypted session thing, so I updated to the image:

ghcr.io/niharmehta/juicepassproxy:latest (I'm running this on a pi3b+) with docker config:

```
  ports:
      - 8042:8047/udp
    environment:
      - JUICEBOX_HOST=192.168.35.220
#      - UPDATE_UDPC=true
      - JPP_HOST=192.168.35.167
      - DST=158.47.1.128
      - EXPERIMENTAL=true
      - IGNORE_ENELX=true
```
 
I've setup reflecting NAT to insert the MITM proxy (this all worked fine before), and blocked port 443 stopping the encrypted session, but still allowing Telent, DNS and NTP.  Logging shows I have a connection to the juicebox via the proxy, but now the behavior has changed

Using sliders within HA, and with 'Act as Server' on:

1. number.juicebox_max_charging_current no longer seems to control the charging current.
2. number.juicebox_max_current_online_wanted does seem to control the charging current
3. ... but if this slider sounds like 'number.juicebox_max_current' which I thought we were supposed to leave alone because it writes eprom.

My question: is my install operating correctly (e.g. using 2. to control the current, or should I still be using 1.?  And where can I find documentation or descriptions about the operation of the new number sliders?  Any help or advice would be welcomed.

**Comment by ivanfmartinez** [comment]
The first versions used number.juicebox_max_charging_current and that value is mixed between what you want and what device is using, then they are separated on "device" and "wanted" values.


The configuration is retained on mqtt, you have to remove the configuration from your MQTT broker and delete the old entity from your HA.

the "Wanted" parameters is the ones that can control the device, the "offline_wanted" is the actual parameter that writes the eeprom as indicated on the README 

https://github.com/JuiceRescue/juicepassproxy/pull/69/files#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aaR236

**Comment by Scott1009** [comment]
Thank you!
